INSERT INTO major_muscle VALUES ("Chest","Also called Pectorals.");
INSERT INTO major_muscle VALUES ("Lats","Latissimus dorsi muscle");
INSERT INTO major_muscle VALUES ("Trapezius","Upper Back");
INSERT INTO major_muscle VALUES ("Deltoids","Shoulders");
INSERT INTO major_muscle VALUES ("Biceps","Front of arms.");
INSERT INTO major_muscle VALUES ("Triceps","Back of arms.");
INSERT INTO major_muscle VALUES ("Forearm","");
INSERT INTO major_muscle VALUES ("Abdomen","");
INSERT INTO major_muscle VALUES ("Obliques","");
INSERT INTO major_muscle VALUES ("Lower Back","");
INSERT INTO major_muscle VALUES ("Hips","");
INSERT INTO major_muscle VALUES ("Gluts","Also called Buttocks.");
INSERT INTO major_muscle VALUES ("Quadriceps","Front of thighs.");
INSERT INTO major_muscle VALUES ("Hamstring","Back of thighs.");
INSERT INTO major_muscle VALUES ("Adductors","Inside of thighs.");
INSERT INTO major_muscle VALUES ("Calves","");



INSERT INTO exercise (name) VALUES ("Conventional Deadlift");
INSERT INTO exercise (name) VALUES ("Romanian Deadlift");
INSERT INTO exercise (name) VALUES ("Straight-legged Deadlift");
INSERT INTO exercise (name) VALUES ("Sumo Deadlift");
INSERT INTO exercise (name) VALUES ("Trap Bar Deadlift");
INSERT INTO exercise (name) VALUES ("Back Squat");
INSERT INTO exercise (name) VALUES ("Front Squat");
INSERT INTO exercise (name) VALUES ("Box Squat");
INSERT INTO exercise (name) VALUES ("Sumo Squat");
INSERT INTO exercise (name) VALUES ("Overhead Squat");
INSERT INTO exercise (name) VALUES ("Split Squat");
INSERT INTO exercise (name) VALUES ("Smoth Squat");
INSERT INTO exercise (name) VALUES ("Bodyweight Squat");
INSERT INTO exercise (name) VALUES ("Jump Squat");
INSERT INTO exercise (name) VALUES ("Flat Barbell Bench Press");
INSERT INTO exercise (name) VALUES ("Incline Barbell Bench Press");
INSERT INTO exercise (name) VALUES ("Decline Barbell Bench Press");
INSERT INTO exercise (name) VALUES ("Flat Dumbbell Bench Press");
INSERT INTO exercise (name) VALUES ("Incline Dumbbell Bench Press");
INSERT INTO exercise (name) VALUES ("Decline Dumbbell Bench Press");
INSERT INTO exercise (name) VALUES ("Chest Fly");
INSERT INTO exercise (name) VALUES ("Dips");
INSERT INTO exercise (name) VALUES ("Pull-up");
INSERT INTO exercise (name) VALUES ("Pull-down");
INSERT INTO exercise (name) VALUES ("Chin-up");
INSERT INTO exercise (name) VALUES ("Muscle-up");
INSERT INTO exercise (name) VALUES ("Seated Row");
INSERT INTO exercise (name) VALUES ("Face Pull");
INSERT INTO exercise (name) VALUES ("Shoulder Shrug");
INSERT INTO exercise (name) VALUES ("Upright Row");
INSERT INTO exercise (name) VALUES ("Bent-over Row");
INSERT INTO exercise (name) VALUES ("Bridge");
INSERT INTO exercise (name) VALUES ("Front raise");
INSERT INTO exercise (name) VALUES ("lateral Raise");
INSERT INTO exercise (name) VALUES ("Military Press");
INSERT INTO exercise (name) VALUES ("Overhead Press");
INSERT INTO exercise (name) VALUES ("Biceps Curl");
INSERT INTO exercise (name) VALUES ("Wirst Curl");
INSERT INTO exercise (name) VALUES ("Crunch");
INSERT INTO exercise (name) VALUES ("Leg Raise");
INSERT INTO exercise (name) VALUES ("Sit-Up");
INSERT INTO exercise (name) VALUES ("Plank");
INSERT INTO exercise (name) VALUES ("Good-morning");
INSERT INTO exercise (name) VALUES ("Hyperextension");
INSERT INTO exercise (name) VALUES ("Leg Press");
INSERT INTO exercise (name) VALUES ("Lunge");
INSERT INTO exercise (name) VALUES ("Calf Raise");